# Generated by Django 4.0.6 on 2022-08-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('Email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
    ]
