# Generated by Django 4.1 on 2022-08-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
