# Generated by Django 4.1 on 2022-08-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
        ('Cliente', '0003_prestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sucursal.sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('C', 'Classic'), ('G', 'Gold'), ('B', 'Black')], default='C', max_length=1),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
