# Generated by Django 4.1 on 2022-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.IntegerField(max_length=20, verbose_name='numero_tarjeta')),
                ('cvv', models.IntegerField(max_length=4, verbose_name='cvv')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('fecha_expiracion', models.DateField(verbose_name='fecha_expiracion')),
            ],
        ),
    ]
