# Generated by Django 4.1 on 2022-08-13 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_delete_empleado_delete_prestamo_and_more'),
        ('Tarjeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='cvv',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='cvv'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=20, verbose_name='numero_tarjeta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('C', 'CREDITO'), ('D', 'DEBITO')], max_length=2),
        ),
    ]
