# Generated by Django 4.1 on 2022-08-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_delete_empleado_delete_prestamo_and_more'),
        ('Tarjeta', '0002_tarjeta_cliente_alter_tarjeta_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
    ]
