# Generated by Django 4.1 on 2022-08-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0004_delete_empleado_delete_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('categoria', models.CharField(max_length=255, verbose_name='categoria')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('importe', models.FloatField(verbose_name='importe')),
                ('saldo', models.FloatField(verbose_name='saldo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
