# Generated by Django 4.1 on 2022-08-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelTable(
            name='movimiento',
            table='movimientos',
        ),
    ]
