# Generated by Django 4.1 on 2022-08-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table='Cuenta',
        ),
    ]
