# Generated by Django 4.1 on 2022-08-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_delete_empleado_delete_prestamo_and_more'),
        ('Prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Tipo',
            field=models.CharField(choices=[('HTO', 'HIPOTECARIO'), ('PDO', 'PRENDARIO'), ('PRL', 'PERSONAL')], default='HTO', max_length=3),
        ),
    ]
